### PR TITLE
feat(network): support buffering transfer-encoding: chunked

### LINKED ISSUE #165: `Transfer-Encoding: chunked` response support
## Feature Request

Remove chunked encoding on responses instead of letting the encoding go through and have a `content-length` be calculated including the encoding.

**Is your feature request related to a problem? Please describe.**

When `curl`'d via an AWS ALB, the route below returns the result below, which includes the chunked response encoding control bytes in the response payload.

```
< HTTP/2 200 
< server: awselb/2.0
< date: Mon, 01 Jan 2024 05:58:45 GMT
< content-type: text/plain
< content-length: 65
< x-powered-by: Express
< 
19
INITIAL PAYLOAD RESPONSE

17
FINAL PAYLOAD RESPONSE

0
```

Express Route:

```
app.get("/chunked-response", async (req, res) => {
  // Send headers right away
  res.setHeader("Content-Type", "text/plain");
  res.setHeader("Transfer-Encoding", "chunked");
  res.status(200);

  // Send initial payload
  res.write("INITIAL PAYLOAD RESPONSE\n");

  // Wait for 5 seconds
  await sleep(5000);

  // Send final payload and close out the response
  res.end("FINAL PAYLOAD RESPONSE\n");
});
```

**Describe the solution you'd like**

I don't believe an ALB invoking a Lambda supports `Transfer-Encoding: chunked` at all, but there are cases where code will exist that writes the response as chunked because it doesn't know the content length ahead of time.  Yes, in that case the entire response is going to be buffered within the Lambda so the length will end up being known.

It would be beneficial if the `Transfer-Encoding: chunked` header was stripped and the control characters were removed before the response body was returned, OR, at the very least throw a nasty exception if a `Transfer-Encoding: chunked` response header is encountered.

**Describe alternatives you've considered**

Not using `Transfer-Encoding: chunked`... however, the specific case that I'm handling is a comparison test of when the first bytes to a response arrive from this invocation method vs via another method that I'm working on, so I have to use chunked if I want the Express code to be compariable.

## Are you willing to resolve this issue by submitting a Pull Request?

Potentially.

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

### PR DESCRIPTION
**Pull request by H4ad**
Closes #165

### CODE REVIEW

**Comment by huntharo** [comment]
I cannot positively tell if this is going to work.

I'm looking for the place where it reads the first chunk length, skips the trailing `\r\n` after that chunk length, then copies the bytes of the specified length after that, then reads the next chunk length, skips the trialing `\r\n` again, reads the byte length specified, etc.  I can't find that place but I might just be overlooking it.

I don't think we need to set the content-length header in the response because the Lambda will do that when we give it the body string or base64 encoded body value.

I'm also confused as to why there is still an option to throw an exception on chunked encoding for API Gateway V1 since we should always be stripping out the chunked response encoding?

But... it looks really good and either perfect or very close!

**Comment by H4ad** [comment]
> I'm looking for the place where it reads the first chunk length, skips the trailing \r\n after that chunk length, then copies the bytes of the specified length after that, then reads the next chunk length, skips the trialing \r\n again, reads the byte length specified, etc. I can't find that place but I might just be overlooking it.

The chunk came in the following order:

```
HTTP/2 200 
server: awselb/2.0
date: Mon, 01 Jan 2024 05:58:45 GMT
content-type: text/plain
content-length: 65
x-powered-by: Express
\r\n19
```

```
\r\n
```

```
INITIAL PAYLOAD RESPONSE\n
```

```
17
```

```
\r\n
```

```
FINAL PAYLOAD RESPONSE\n
```

```
0\r\n\r\n
```

I basically need to ignore the first chunk, skip the second, take the third chunk, and then skip the next 2 chunks, and keep going until I find the endChunk.

The chunks will always be sent `size`, `delimiter`, and then `data`.

The code that handles this algorithm is https://github.com/H4ad/serverless-adapter/pull/167/files#diff-4f134ef86a335c260c3933721a28831071072ecafbafb3252e42cc2972d5bbf2R80-R84
Is the same logic I use for my `Streaming Response` support.

And from the tests, I worked without issues.

> I'm also confused as to why there is still an option to throw an exception on chunked encoding for API Gateway V1 since we should always be stripping out the chunked response encoding?

Because it's a breaking change, and I don't want to release a major version, so I will just keep the same behavior and let the people explicitly use that option to enable the support, in the next major version, I can invert the value and keep that `throw` as `false`.

**Comment by huntharo** [comment]
Thanks for the details!  Sounds good to me.

**Review by huntharo — APPROVED** [review]
LGTM (not that I can approve)

**Comment by H4ad** [comment]
Thanks for the review.

**Pull request merged**
